[class]
audio_default	= [
	{ command = "mpv", args = [ "--" ], fork = true, silent = true },
]

image_default	= [
	{ command = "feh", args = [ "--" ], fork = true, silent = true },
]

video_default	= [
	{ command = "mpv", args = [ "--" ] , fork = true, silent = true },
]

text_default	= [
	{ command = "nvim" },
	{ command = "vim", fork = true, silent = true },
]

reader_default	= [
	{ command = "zathura", fork = true, silent = true },
]

[extension]

## image formats
avif.inherit	= "image_default"
bmp.inherit	= "image_default"
gif.inherit	= "image_default"
heic.inherit	= "image_default"
jpeg.inherit	= "image_default"
jpe.inherit	= "image_default"
jpg.inherit	= "image_default"
pgm.inherit	= "image_default"
png.inherit	= "image_default"
ppm.inherit	= "image_default"
webp.inherit	= "image_default"
svg.inherit	= "image_default"

## audio formats
flac.inherit	= "audio_default"
m4a.inherit	= "audio_default"
mp3.inherit	= "audio_default"
ogg.inherit	= "audio_default"
webm.inherit	= "audio_default"
wav.inherit	= "audio_default"

## video formats
avi.inherit	= "video_default"
av1.inherit	= "video_default"
flv.inherit	= "video_default"
mkv.inherit	= "video_default"
m4v.inherit	= "video_default"
mov.inherit	= "video_default"
mp4.inherit	= "video_default"
rmvb.inherit	= "video_default"
wmv.inherit	= "video_default"

## text formats
build.inherit	= "text_default"
c.inherit	= "text_default"
cmake.inherit	= "text_default"
conf.inherit	= "text_default"
cpp.inherit	= "text_default"
css.inherit	= "text_default"
csv.inherit	= "text_default"
cu.inherit	= "text_default"
ebuild.inherit	= "text_default"
eex.inherit	= "text_default"
env.inherit	= "text_default"
ex.inherit	= "text_default"
exs.inherit	= "text_default"
go.inherit	= "text_default"
h.inherit	= "text_default"
hpp.inherit	= "text_default"
hs.inherit	= "text_default"
lhs.inherit	= "text_default"
html.inherit	= "text_default"
ini.inherit	= "text_default"
java.inherit	= "text_default"
js.inherit	= "text_default"
json.inherit	= "text_default"
kt.inherit	= "text_default"
lua.inherit	= "text_default"
log.inherit	= "text_default"
md.inherit	= "text_default"
micro.inherit	= "text_default"
ninja.inherit	= "text_default"
py.inherit	= "text_default"
rkt.inherit	= "text_default"
rs.inherit	= "text_default"
scss.inherit	= "text_default"
sh.inherit	= "text_default"
sol.inherit	= "text_default"
srt.inherit	= "text_default"
svelte.inherit	= "text_default"
toml.inherit	= "text_default"
ts.inherit	= "text_default"
tsx.inherit	= "text_default"
txt.inherit	= "text_default"
vim.inherit	= "text_default"
xml.inherit	= "text_default"
yaml.inherit	= "text_default"
yml.inherit	= "text_default"

# archive formats
7z.app_list	= [
	{ command = "7z", args = [ "x" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
bz2.app_list	= [
	{ command = "tar", args = [ "-xvjf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
gz.app_list	= [
	{ command = "tar", args = [ "-xvzf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
tar.app_list	= [
	{ command = "tar", args = [ "-xvf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
tgz.app_list	= [
	{ command = "tar", args = [ "-xvzf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
rar.app_list	= [
	{ command = "unrar", args = [ "x" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
xz.app_list	= [
	{ command = "tar", args = [ "-xvJf" ], confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]
zip.app_list	= [
	{ command = "unzip", confirm_exit = true },
	{ command = "file-roller", fork = true, silent = true } ]

odt.inherit	= "libreoffice_default"
odf.inherit	= "libreoffice_default"
ods.inherit	= "libreoffice_default"
odp.inherit	= "libreoffice_default"

doc.inherit	= "text_default"
docx.inherit	= "text_default"
xls.inherit	= "text_default"
xlsx.inherit	= "text_default"
ppt.inherit	= "text_default"
pptx.inherit	= "text_default"

pdf.inherit	= "reader_default"
djvu.inherit = "reader_default"

kra.app_list = [
	{ command = "krita", fork = true, silent = true }
]

tex.app_list	= [
	{ command = "nvim" },
	{ command = "vim", fork = true, silent = true },
	{ command = "pdflatex" } ]

